version: 2.1

jobs:
  build:
    working_directory: ./src
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install python packages
          command: |
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt"}}
          paths:
            - "venv"

      - run:
          name: Run tests
          command: python -m pytest
